# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 14:12
from __future__ import unicode_literals

import data.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True, validators=[data.models.data_exist])),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.UUIDField(default=data.models.generate_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
